name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn build
        env:
          DATO_API_TOKEN: ${{ secrets.DATO_API_TOKEN }}
      - run: yarn deploy-ftp
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWD: ${{ secrets.FTP_PASSWD }}
      # - name: FTP Deploy
      #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
      #   with:
      #     log-level: verbose
      #     server: ftp.webarts.pl
      #     username: piotrek
      #     password: ${{ secrets.ftp_password }}
      #     local-dir: public/
      #     server-dir: /domains/webarts.pl/public_html/
