name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn build
        env:
          DATO_API_TOKEN: ${{ secrets.DATO_API_TOKEN }}
      - run: ls
      - run: ls public
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.webarts.pl
          username: piotrek
          password: ${{ secrets.ftp_password }}
          local-dir: public/
          server-dir: /domains/webarts.pl/public_html/
